name: 🔨 Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: 🔨 Build and Security Test
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DEV: ${{ secrets.DEV }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      PASSWORD_ENCRYPTION_KEY: ${{ secrets.PASSWORD_ENCRYPTION_KEY }}
      STATIC_URL: ${{ secrets.STATIC_URL }}
      MEDIA_URL: ${{ secrets.MEDIA_URL }}
      LANGUAGE_CODE: ${{ secrets.LANGUAGE_CODE }}
      TIME_ZONE: ${{ secrets.TIME_ZONE }}
      USE_I18N: ${{ secrets.USE_I18N }}
      USE_TZ: ${{ secrets.USE_TZ }}
      SQLITE_NAME: ${{ secrets.SQLITE_NAME }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies and Security Tools
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          pip install -r requirements.txt
          pip install coverage pylint bandit pip-audit

      - name: 🛠️ Apply Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: ✅ Run Unit Tests
        run: python manage.py test

      - name: 📈 Run Tests with Coverage
        run: |
          coverage run manage.py test
          coverage report

      - name: 🧐 Run Pylint (Static Code Analysis)
        run: |
          pylint **/*.py || true

      - name: 🔍 Run Bandit (Security Static Scan)
        run: |
          bandit -r .

      - name: 🔒 Run pip-audit (Dependency Vulnerability Scanner)
        run: |
          pip-audit || true
