name: 🔨 Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: 🔨 Build and Security Test
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_NAME: db.sqlite3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Unit Tests
        run: python manage.py test

      - name: Run Tests with Coverage
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Run Pylint
        run: |
          pip install pylint
          pylint **/*.py || true

      - name: Run Bandit (Python Security Scanner)
        run: |
          pip install bandit
          bandit -r .

      - name: Run pip-audit (Dependency Vulnerability Scanner)
        run: |
          pip install pip-audit
          pip-audit
