name: 🚀 Docker Build and Push

on:
  workflow_run:
    workflows: ["🔨 Build and Test"]
    types:
      - completed

jobs:
  docker-build-and-push:
    name: 🚀 Docker Build and Push
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/keymanager:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/keymanager:latest

      - name: Security Scan with Trivy (Container Vulnerabilities)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/keymanager:latest'
